[project]
name = "abstractions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.11.5",
    "pytest>=8.4.0",
]
